### PR TITLE
Add documentation and example for using TVPType

### PR DESCRIPTION
**Pull request by v-kaywon**

### CODE REVIEW

**Comment by NikitaDef** [comment]
@v-kaywon #453 was merged. 
Will you add into documentation about the tags `tvp` and `json`?

Also TVPType was changed to
```
type TVPType struct {
	TVPTypeName string
	TVPValue interface{}
}
```

**Comment by v-kaywon** [comment]
@NikitaDef Yes I'll be working on that!

**Comment by v-kaywon** [comment]
@NikitaDef There was a small bug in handling `tvpFieldIndexes` and `columnStr` in the `encode` function of `tvp_go19.go`. Say there is a struct with 3 fields:

```
type t struct {
f1 int
f2 int `tvp:"-"`
f3 int
}
```

`columnStr` has a length of 2. At this point `tvpFieldIndexes` looks like this:

```
[0]: 0
[1]: 2
```
If the values of `tvpFieldIndexes` are used to access information in `columnStr`, this will result in a panic since `columnStr[2]` do not exist. The change in this PR uses the key of `tvpFieldIndexes` to access `columnStr` instead.

**Comment by NikitaDef** [comment]
@v-kaywon Thank you for fixing. I forgot about that situation.
I'll add tests than your pull request will be merged

**Comment by NikitaDef** [comment]
@denisenkom @kardianos are you going to merge it?

**Pull request merged**
