### PR TITLE
add date time specific parameter types

### LINKED ISSUE #371: QueryContext  call issue with Datetime type on SQL Server 12
Hi
I'm stuggling with passing a time.Time through as a datetime. Please can anyone help?

I'm calling QueryContext on a stored procedure which takes a datetime (`@dtEffectiveDateTime`) as an input parameter.
```
PROCEDURE [dbo].[UP_SC_GetCountryCodes]
      @iNumbericCode    int     	= 0, -- GET ALL  
      @vcSYSLanguageCode    char(2) 	= 'en',
      @dtEffectiveDateTime   datetime	= '9999-12-31 23:59:59.997',
      @iFirstCode     int   = 0, 
      @iSuccess      bigint  OUTPUT,
      @dtAPIForceCacheRefreshDtTm datetime	OUTPUT
```
My Go (1.10.2) code sets the parameter like this:

```
sql.Named("dtEffectiveDateTime", time.Now().UTC()),
```

However, SQL Server 12 () is returning this error:

```
"mssql: Error converting data type datetimeoffset to datetime."
```

I have tried setting the parameter using a non-inline variable of type Time, being set to either UTC() or with no timezone specifically set (my local timezone is EET), I have also tried using an zero time.Time{} - but all result in the same error message.

A trace off the DB, when using a variable set to time.Time{} gave this information:
```
declare @p5 bigint
set @p5=0
declare @p6 datetimeoffset(7)
set @p6='0001-01-01 00:00:00 +00:00'
exec dbo.UP_SC_GetCountryCodes @iNumbericCode=0,@vcSYSLanguageCode=N'en',@dtEffectiveDateTime='0001-01-01 00:00:00 +00:00',@iFirstCode=0,@iSuccess=@p5 output,@dtAPIForceCacheRefreshDtTm=@p6 output
select @p5, @p6
```

My DBA says the error message is because the time.Time value for the `@dtEffectiveDateTime` parameter is not coming through as a datetime - which makes sense as the offset is present in the trace. 
Is there a way to tell the go-mssqldb driver to convert time.Time into datetime rather than (I think) datetimeoffset ?

I'm using the driver as "sqlserver" 

Many thanks for your time.
Mark.

### PR DESCRIPTION
**Pull request by kardianos**
Fixes #371

### CODE REVIEW

**Comment by kardianos** [comment]
@denisenkom This adds a dependency on civil time. Not sure how you feel about that.

**Comment by MarkSonghurst** [comment]
@kardianos re cloud.google.com/go/civil - not an issue for me. 
Many thanks for the fix, just in time (sorry!) for a new project I'm starting.

**Comment by denisenkom** [comment]
Looks ok to me.  Although I would prefer soft dependency instead of hard dependency, and by soft I mean an optional dependency.

**Comment by kardianos** [comment]
Let me push a little bit harder to make this optional.

**Pull request merged**
