### PR TITLE
bulk copy for decimal types

### PR DESCRIPTION
**Pull request by jackielii**
decimal types first pass. money types should be the same, but not working for some reason. Submitting decimal types only this time

Reference: https://github.com/Microsoft/mssql-jdbc/blob/master/src/main/java/com/microsoft/sqlserver/jdbc/IOBuffer.java#L3307

### CODE REVIEW

**Comment by kardianos** [comment]
@jackielii I appreciate this work. However, I would like to have a full conversation about how decimals are supported end-to-end before doing this. In the mean time feel free to rebase.

Depends on https://github.com/denisenkom/go-mssqldb/issues/245

**Comment by jackielii** [comment]
Thanks for responding!

Are we going to import apd package and should I wait for that to be included to rebase? I suppose we'll deprecate the internal Decimal type and use the apd package?

**Comment by kardianos** [comment]
@jackielii Feel free to rebase now, I may be able to review it and even without full decimal support.

But yes, I'd like to start the conversation on what to do in the driver going forward. No firm plans yet. If you care about this, I'd appreciate some review thought as what to do.

**Comment by jackielii** [comment]
@kardianos rebased

**Comment by kardianos** [comment]
Thanks for the rebase. I'm still planning on looking at this.

**Pull request merged**
