### PR TITLE
Fix bulkcopy of DateTimeOffsets and precise Decimals

### PR DESCRIPTION
**Pull request by jwebb**
- Converting numeric types via float64 risks losing precision, so add direct conversions for ints and strings
- DateTimeOffset values were being rejected by the server due to a typo in the code
- Also support dates/times expressed as strings for consistency with regular inserts, and make the 'invalid type' errors more helpful

### CODE REVIEW

**Comment by jwebb** [comment]
Agree this could do with a larger rework. The `[4]int32` at present is just adding complication with no benefit, as all output conversions go via `big.Int` anyway. The simplistic float64 conversions also have undesirable properties (e.g. round-tripping 1.3 will become 1.2999999999999999245025280). Go provides Grisu3/Dragon4 implementations for this reason.

Thing is, it's not obvious to me that this library needs any sort of decimal type at all. It's public, but it doesn't look like something a client would ever use? Unless there are future plans? Right now AFAICT it's only used momentarily for conversions, and there's very little sharing of code paths. Given that, it would probably be better to implement each of those conversions as a function using whatever library facilities are most appropriate, and ditch the intermediate representation.

(But I still think this PR should be merged in the meantime, as it fixes observable issues.)

**Comment by SQLServerIO** [comment]
I am using github.com/shopspring/decimal to handle all my decimal needs.

**Comment by dagss** [comment]
Nice work I'd really like this in.. 

NOTE: When implementing #430 I first tried introducing a dedicated mssql.Money type for the bulk import. However, the golang `database/sql` package didn't like that -- it seems that arguments has to be converted to primitive types before they hit the driver.

So I think this PR would need to work with string -- any decimal type would need to serialize to string before it is allowed to hit this driver code.

*On tests*:

I notice that the strategy used for testing conflicts with the one I did in #430 . I did that what I did so that it would be possible to test for bulk import of NULL values, but I can rewrite the test to follow the pattern here if required.

**Comment by j0hnwhyte** [comment]
Is it possible to fix at least the `datetimeoffset` issue? I can see that using `datetime2` works when using the bulk insert feature, and I'm currently using it as a workaround.

**Comment by denisenkom** [comment]
Yes, please send PR which contains fix for datetime2 issue.  Or provide details about this issue, preferably by opening issue or linking issue, if one already open.

**Comment by jwebb** [comment]
This PR already contains the fix. As well as another. Can I please understand why you will not merge it?

I'm happy to rebase, if it's going to be merged.

I'm also happy to spend some time on refactoring to remove the Decimal type entirely as I mentioned previously. But I'd first need some feedback from you that this is a direction you want to go in, and I don't think that reworking internals should hold up a fix for a data corruption issue.

In the meantime, we have been using this branch in production for the past year.

**Comment by denisenkom** [comment]
This PR is too big.  Maybe you can break it down into individual fixes.  Lets start with datetime fix. I still don't know what is wrong with it, but with smaller PR I might be able to understand.
There is no good solution for decimals yet, so lets postpone it.  I believe newer golang will have necessary functionality, once it is ready we can revisit.

**Comment by j0hnwhyte** [comment]
The problem I'm having is that if I use that SQL type for the column definition, the bulk insert operation fails, while if the column uses the `datetime2` type everything works.

**Comment by jwebb** [comment]
Datetimeoffsets are this commit - a trivial typo: https://github.com/denisenkom/go-mssqldb/pull/404/commits/bcb7c743efe7c0e8f456e166990d79d4c107d34b

I could PR these separately if necessary, and if it will result in everything going in. But I'm afraid that much as I would prefer to contribute fixes back, I can't reasonably allocate time to work on this further if we're going to have to continue to use our own fork anyway.

I must say I'm a little confused by the position that it is better not to apply a fix for a data corruption bug now (or indeed a year ago!), just because the code might be deleted later if something better comes along. Nothing in this fix would make that work any harder. Easier, in fact, given that it also improves error reporting and test coverage.

**Comment by denisenkom** [comment]
Ok merged datetimeoffsets fix.  I will look more into the reset of this PR.
In general it is better when PR contains single fix, especially when it introduces lots of changes.  Otherwise it make is much harder to review.

**Comment by denisenkom** [comment]
I reviewed the rest of the changes, and I approve this PR.  @jwebb can you re-base it?

**Comment by jwebb** [comment]
Great, thanks!

Rebasing a branch this old was slightly nontrivial, so I'm going to do some more testing before updating this PR (rebase is at https://github.com/XTXMarkets/go-mssqldb/commits/bulk-insert2 if anyone's curious). Will check back in, in a day or so.

**Comment by jwebb** [comment]
Seems fine. Updated.

**Pull request merged**
