### PR TITLE
Fix civil mod config

### PR DESCRIPTION
**Pull request by jjafuller**

### CODE REVIEW

**Comment by kardianos** [comment]
I don't think you intended to create this pull request. Confirm?

**Comment by jjafuller** [comment]
Correct. My apologies.

**Comment by kardianos** [comment]
@jjafuller Out of curiosity, any particular reason you are forking it?

**Comment by jjafuller** [comment]
> @jjafuller Out of curiosity, any particular reason you are forking it?

That is a good question. I think at the time it was forked this module depended on cloud.google.com/go/civil which doesn't work in aws? I'll follow up with our maintainer to see if we actually still need a fork of this.

**Pull request closed without merging**
