### PR TITLE
support money type for bulk copy

### PR DESCRIPTION
**Pull request by iporer**
support money type for bulk copy.
Changes have applied on my project and worked.
Please review it and consider merge it.

### CODE REVIEW

**Comment by denisenkom** [comment]
Can you add tests for new code?

**Comment by iporer** [comment]
@denisenkom tests added. Please review.

**Comment by SQLServerIO** [comment]
The conversion to float is incorrect. 
Since money is a fixed point data type I recommend converting it to string then properly filling the buffer so you don't get unexpected results.
This is what I'm doing right now I'm sure there is a better way. I ether convert to a string or use the decimal package and it converts it to a string.

		var value float64
		if col.ti.Size == 4 {
			res.ti.Size = 4
			res.buffer = make([]byte, 4)
			var i32 uint32
			switch v := val.(type) {
			case string:
				if strings.Contains(v, ".") {
					pointLoc := strings.Index(v, ".")
					intStr := strings.Split(v, ".")
					i64, _ := strconv.ParseInt((intStr[0] + intStr[1]), 10, 64)
					var i, e = big.NewInt(10), big.NewInt(int64((pointLoc)))
					i.Exp(i, e, nil)
					i64 = i64 * i.Int64()
					i32 = uint32(i64 * 10 * int64(pointLoc))
				}
			}
			binary.LittleEndian.PutUint32(res.buffer, i32)
		} else if col.ti.Size == 8 {
			res.ti.Size = 8
			res.buffer = make([]byte, 8)
			var high uint32
			var low uint32
			switch v := val.(type) {
			case int:
				value = float64(v)
				intValue := int64((value + 0.000000000000001) * 10000)
				high = uint32(intValue >> 32)
				low = uint32(intValue - int64(high))
			case int8:
				value = float64(v)
				intValue := int64((value + 0.000000000000001) * 10000)
				high = uint32(intValue >> 32)
				low = uint32(intValue - int64(high))
			case int16:
				value = float64(v)
				intValue := int64((value + 0.000000000000001) * 10000)
				high = uint32(intValue >> 32)
				low = uint32(intValue - int64(high))
			case int32:
				value = float64(v)
				intValue := int64((value + 0.000000000000001) * 10000)
				high = uint32(intValue >> 32)
				low = uint32(intValue - int64(high))
			case int64:
				value = float64(v)
				intValue := int64((value + 0.000000000000001) * 10000)
				high = uint32(intValue >> 32)
				low = uint32(intValue - int64(high))

			case string:
				var intValue int64
				if strings.Contains(v, ".") {
					intStr := strings.Split(v, ".")

					bnoden := intStr[1]
					if len(intStr[1]) > 4 {
						intStr[1] = bnoden[0:4]
					}
					if len(intStr[1]) == 1 {
						intStr[1] = intStr[1] + "0"
					}
					if len(intStr[1]) == 3 {
						intStr[1] = intStr[1] + "0"
					}

					i64, _ := strconv.ParseInt((intStr[0] + intStr[1]), 10, 64)

					if len(intStr[1]) == 2 {
						intValue = i64 * 100
					}
					if len(intStr[1]) == 4 {
						intValue = i64
					}

					high = uint32(intValue >> 32)
					low = uint32(intValue - int64(high))
				} else {
					value, _ = strconv.ParseFloat(v, 64)
					intValue := int64((value + 0.000000000000001) * 10000)
					high = uint32(intValue >> 32)
					low = uint32(intValue - int64(high))
				}
			}

			binary.LittleEndian.PutUint32(res.buffer[0:4], high)
			binary.LittleEndian.PutUint32(res.buffer[4:8], low)
		} else {
			err = fmt.Errorf("mssql: invalid size of money column")
		}

**Comment by kardianos** [comment]
We need to do a better job integrating decimal types across the board.

**Comment by kardianos** [comment]
I fully want to support Money and Decimal types. But converting them to float64 isn't how I want to do it.

**Pull request closed without merging**
