### PR TITLE
Azure Active Directory authentication

### LINKED ISSUE #446: Azure Active Directory Authentication is not supported?
Hi,

I am able to connect to Azure database using SQL authentication but when I use [Azure AD](https://docs.microsoft.com/en-us/azure/sql-database/sql-database-aad-authentication) credentials I receive TLS handshake error when pinging the database:
`Cannot read handshake packet: read tcp: wsarecv: An existing connection was forcibly closed by the remote host.`

Connection String:
`sqlserver://user:pass@database.windows.net:1433?app+name=MyAppName&database=dbname&encrypt=true&hostNameInCertificate=%2A.database.windows.net&trustservercertificate=true`

Is the Azure AD supported or not?

Thanks

### PR DESCRIPTION
**Pull request by paulmey**
Merging #547 and #546 to fully fix #446

### CODE REVIEW

**Comment by kardianos** [comment]
@paulmey 
What's the current status on this PR? I see it merges two other PRs, one from you and another from @wrosenuance . I'm assuming it isn't ready yet for review due to draft status, correct?

Lastly, how would you propose we test (CI) this code so it doesn't break? SQL Server (hosted) has a free dev license, but this looks like Azure specific?

**Comment by kardianos** [comment]
Okay, I just read through the Issue history. I think I understand the situation now.

I assume we will keep this PR a s a draft and NOT merge it, but rather merge each contribution by itself.

**Comment by wrosenuance** [comment]
@kardianos I was not sure which way to go for CI. I don't know of services that would allow for running actual tests against an Azure AD authenticated service, let alone run with access to the managed service identity endpoint used for some of the scenarios.

I see that @paulmey has added some tests at a protocol level, which is one avenue, the other might be to try to bring in some sort of mocking framework to help by abstracting the Azure-specific code.

I ran most of my tests by spinning up actual Azure infrastructure, using the Terraform example and a Pay-As-You-Go account, and I am also using the code at my company where they are using Azure infrastructure that supports the MSI and AD user logins.

**Comment by paulmey** [comment]
@kardianos, I mainly started this PR to merge the approaches and bring the code coverage up with some more "unit" tests that don't need a real instance. I'm also fine with seeing if we can provide a SQL Azure instance for CI, but it will be a bit of work in appveyor etc. to keep credentials secret and fresh...?
@wrosenuance please feel free to steal the test code as your own if it seems useful for your PR, I can rebase the access token connector on top of it.

**Comment by wrosenuance** [comment]
Hi @paulmey, as your original changes were merged first, I rebased #547 on top of them. So far I have not tried to add in your new tests from this PR while waiting for confirmation that the revisions I'm proposing are on the right track. I am happy to do the work to bring them over, though! I think I have broken the merge for this PR after rebasing.

**Comment by paulmey** [comment]
Feel free to bring over the tests, this branch will stay around. Aborting this PR.

**Pull request closed without merging**
