### PR TITLE
Add ability to set a custom logger

### PR DESCRIPTION
**Pull request by polarina**

### CODE REVIEW

**Comment by denisenkom** [comment]
Why not call http://golang.org/pkg/log/#SetOutput instead?

**Comment by polarina** [comment]
The problem with simply using `SetOutput` is that it I have no way of determining from which MSSQL connection the logs originate. I am using multiple databases concurrently (each in its own goroutine) and I need to know which connection made which log entry.

**Comment by denisenkom** [comment]
I see, then it would be better to set MssqlDriver.log to default logger, that would simplify code.
So instead:

`log.Println(s.query)`

you would do

`s.c.sess.log.Println(s.query)`

**Comment by polarina** [comment]
The default logger is some special snowflake such that you cannot get a `*Logger` handler to it. I don't know why they decided to not expose it.

**Comment by dimdin** [comment]
You can add a log method in the driver with the if logic

**Comment by denisenkom** [comment]
You can also define a new class for default logger which would call default logger methods.

**Comment by polarina** [comment]
No problem. Done. What do you think?

**Comment by dimdin** [comment]
it is ok for me. @denisenkom ?

**Comment by denisenkom** [comment]
I was thinking about slightly different solution.  With DefLogger class implementing Logger interface which calls default logger methods.  And switching loggers is done via changing MssqlDriver.log pointer.
It would be slightly better because call to log.Printf would call your logger directly instead doing a hop through current Logger class.  What do you think @polarina @dimdin ?

**Comment by polarina** [comment]
Unfortunately, `log.Logger` is a struct and not an interface. http://golang.org/pkg/log/#Logger

**Comment by denisenkom** [comment]
Here is what I meant:

define class

```
type StdLogger log.Logger

func (logger *StdLogger) Printf(format string, v ...interface{}) {
	log.Printf(format, v...)
}

...

# in MssqlDriver constructor
  ...
  d.log = new(StdLogger)
  ...
```

Something like that.  Does it make sense now?

**Comment by polarina** [comment]
Wouldn't that imply that `log` in `MssqlDriver` have to be of type `StdLogger`? We can't cast an arbitrary `log.Logger` to `StdLogger`.

**Comment by denisenkom** [comment]
No, why?  It would be of type log.Logger.  StdLogger implements log.Logger interface.

**Comment by polarina** [comment]
Last I checked, `log.Logger` is not an interface.

**Comment by denisenkom** [comment]
Right: http://comments.gmane.org/gmane.comp.lang.go.general/121533

Then I guess we could define an ILogger interface and have StdLogger to implement it, and MssqlDriver.log would have type ILogger.

Something like that, what do you think?

**Comment by dimdin** [comment]
@denisenkom even if we implement it, the calling interface will remain the same (i.e. driver.Printf() and not log.Printf()) I find no reason to implement something like that

**Comment by denisenkom** [comment]
Ok, fine with me.

**Pull request merged**
