### PR TITLE
Change const decls to use iota where possible

### PR DESCRIPTION
**Pull request by infogulch**
There are several large const blocks that just list integers. This is why we have iota. 😄

Thoughts?

### CODE REVIEW

**Comment by dimdin** [comment]
I disagree. These values are defined in the TDS protocol; I don't want to act as a compiler to validate that the correct value is assigned.

**Comment by infogulch** [comment]
Fair enough.

It seems the `prelogin*`, `encrypt*`, `env*`, and `isolation*` constants are explicitly listed on msdn, and I agree that it's reasonable to also list these explicitly.

However, OptionFlags2 (`f*` constants) are described "Represented in least significant bit order." in a list without explicit values, which certainly hints at using iota.

So how about reverting the changes to explicitly listed constants but keeping the `f*` constants and log?

**Comment by dimdin** [comment]
I agree to use iota for the f and log constants.

**Comment by infogulch** [comment]
The mentioned adjustments are now made to the PR (after some mucking around with git).

There are two sets of f* constants. Both are described as bit fields on msdn so both now use iota.

I added a newline before the import for `golang.org/x/net/context` so gofmt doesn't try to sort it with the rest of the imports, keeping it in the same relative position.

I also added the fUserType 3-bit constant that is listed on msdn, but was not present here.

**Comment by kardianos** [comment]
This PR needs to be rebased.

I would strongly prefer to just use iota for log consts, but I'll defer to @dimdin .

**Comment by kardianos** [comment]
Timedout

**Comment by joetaber** [comment]
The value this PR added at the end seemed to be smaller than the downsides of unnecessary churn.

Sorry, I should have closed this earlier.

**Pull request closed without merging**
