### PR TITLE
Support register custom dialer so that it can dial from private networks

### PR DESCRIPTION
**Pull request by shuoyang2016**
Support register custom dialer so that it can dial from networks other than just tcp.

### CODE REVIEW

**Comment by shuoyang2016** [comment]
Just added the unit test. PTAL

**Comment by kardianos** [comment]
Hi @shuoyang2016 I'm sorry I wasn't able to review this sooner. I'm really not keen on a package global registry of dialers. I don't think this needs to (or should) go through a DSN. 

For reference, the linked issue is #433 .

I can take a look at options a bit later.

**Comment by shuoyang2016** [comment]
@kardianos No worries at all :) Now is holiday season so I didn't expect any reply soon.

Feel free to take your time on other options. I proposed this because the same idea is being used on mysql driver. But also feel free to let me know your concerns if I can help resolve some of those.

Happy holiday!

**Comment by shuoyang2016** [comment]
@kardianos  Have you come up with something alternative?

**Comment by shuoyang2016** [comment]
@kardianos Just want to follow up on the status because my team is kinda blocked on this decision and we don't have good alternatives. It is really nice of you if you could help us on this.

Also if you are busy, is there someone you can delegate to that we can talk to them?

**Comment by kardianos** [comment]
Please see #439 for implementation.

**Comment by kardianos** [comment]
@shuoyang2016 Please pull down a copy of #439 and test in your use case locally.

**Comment by shuoyang2016** [comment]
This pr got rejected and I'll close it. #439 is the final accepted pr.

**Pull request closed without merging**
