### PR TITLE
Add support for namespace syntax

### PR DESCRIPTION
**Pull request by DemonVex**
Fix for broken namespace syntax e.g. "SELECT geography::Point(47.65100, -122.34900, 4326)"

### CODE REVIEW

**Comment by denisenkom** [comment]
I think this implementation isn't flexible enough.  How about following logic:

single colon represents parameter
double colon means escape for single colon
here are examples:

:a -> @a
:: -> :
:::: -> ::
:::::: -> ::::
:::a -> :@a

if we leave your logic it would be impossible to represent things like :::

**Comment by DemonVex** [comment]
It makes sense. But it make things more complicated. Where can we use ":::"?
In this case I prefer to use something like "SELECT [geography]::[Point](47.65100, -122.34900, 4326)". It'll even work without this PR and it's valid tsql code unlike "SELECT geography::::Point(47.65100, -122.34900, 4326)".

**Comment by denisenkom** [comment]
Another approach would be to drop query preprocessing.  That is what ADODB does, but I don't know yet how to do it in a way that is backward compatible.

**Comment by kardianos** [comment]
@denisenkom I don't think there is a way to drop it without breaking people.

What if it registered two drivers: "mssql" and "sqlserver". mssql would behave as-is today, while "sqlserver" would drop all pre-processing. We would document the heck out of that behavior in the README and godoc.

**Comment by kardianos** [comment]
I'm closing this in favor of dropping query preprocessing for now.

**Pull request closed without merging**
