### PR TITLE
Update mssql.go

### PR DESCRIPTION
**Pull request by zensqlmonitor**
Comment lines 265 & 266 as workaround for using T-SQL flags

### CODE REVIEW

**Comment by zensqlmonitor** [comment]
As described here : https://github.com/denisenkom/go-mssqldb/issues/138

**Comment by mavlyutov** [comment]
+1
that fix works for me as well

**Comment by dstroot** [comment]
+1 same issue and fix works!!  Let's get this merged.  ;)

**Comment by denisenkom** [comment]
Thanks!

**Pull request merged**
