### PR TITLE
Workaround for Go 1.16

### PR DESCRIPTION
**Pull request by robinknaapen**
This PR should workaround the issues regarding to the tls changes in Go 1.16.

**This is by no means a proper fix**
I do not have enough knowledge about the foundation of the tls package. I can only confirm that the changes fixed my issues.

### CODE REVIEW

**Comment by robinknaapen** [comment]
I noticed https://github.com/denisenkom/go-mssqldb/pull/640, this PR contains infinite recursion on `tlsHandshakeConn`

This should fix the issues in https://github.com/denisenkom/go-mssqldb/issues/639

**Comment by uvw** [comment]
Any chance we could see this PR reviewed/merged soon?

**Comment by kedlas** [comment]
Hope to see this merged soon too.

**Comment by prochac** [comment]
Author's GitHub activity seems pretty poor.

**Comment by zapodot** [comment]
Any chance of a new release containing this fix?

**Comment by denisenkom** [comment]
Published https://github.com/denisenkom/go-mssqldb/releases/tag/v0.10.0

**Pull request merged**
