### PR TITLE
fix timeout issue

### LINKED ISSUE #119: Connection left in bad state after a timeout
I have an issue where my connection is left in a bad state after a timeout or a very slow answer. 

Here's a paste of my log, with log level set to 63. To explain a little what you see;
One "query" is really two queries, first one to mymeta (called the meta query from now on), and given the response from that one to mydata.response (called the data query from now on). The expected result from mymeta is {string, int}, and expected result from mydata is {timestamp, float}
All the queries below are the same queries over and over.
The server is an MSSQL 2012
The names and conditions are fake, but the log is copied from real executions. There's nothing fancy going on in the real query.

First query. Meta query already executed with no problem. Log left out as this is long as it is:

```
2015/08/19 10:06:59 Querying data from hour
2015/08/19 10:06:59 SELECT ts, col FROM mydata.hour WHERE id = @p1 AND ts BETWEEN @p2 AND @p3
2015/08/19 10:06:59     @p1 10305
2015/08/19 10:06:59     @p2 2015-07-11 00:00:00 +0000 UTC
2015/08/19 10:06:59     @p3 2015-08-12 00:00:00 +0000 UTC
2015/08/19 10:07:29 SELECT ts, col FROM mydata.hour WHERE id = @p1 AND ts BETWEEN @p2 AND @p3
2015/08/19 10:07:29     @p1 10305
2015/08/19 10:07:29     @p2 2015-07-11 00:00:00 +0000 UTC
2015/08/19 10:07:29     @p3 2015-08-12 00:00:00 +0000 UTC
2015/08/19 10:08:25 Error when fetching data: read tcp mymssqlserver:1433: i/o timeout
```

Second query. Fails on meta query:

```
2015/08/19 10:08:53 SELECT f1,f2 FROM mymeta WHERE conditions = 1
2015/08/19 10:08:53 Error when fetching data: Error while finding finest aggregation level: Error when finding finest agg: mssql.StreamError=Invalid TDS stream: Unknown token type: 122
```

Third query. Fails on meta query:

```
2015/08/19 10:10:33 SELECT f1,f2 FROM mymeta WHERE conditions = 1
2015/08/19 10:10:33 Error when fetching data: Error while finding finest aggregation level: Error when finding finest agg: mssql.StreamError=Invalid TDS stream: Unknown token type: 101
```

Forth query. Succeeds with meta query. Notice how the raw results here are the expected results from a meta query, but the query was actually a data query:

```
2015/08/19 10:19:38 Querying data from hour
2015/08/19 10:19:38 SELECT dt, S4517B FROM mydata.hour WHERE id = @p1 AND ts BETWEEN @p2 AND @p3
2015/08/19 10:19:38     @p1 10305
2015/08/19 10:19:38     @p2 2015-07-11 00:00:00 +0000 UTC
2015/08/19 10:19:38     @p3 2015-08-12 00:00:00 +0000 UTC
2015/08/19 10:19:38 (3 row(s) affected)
2015/08/19 10:19:38 Problem while scanning query result: sql: Scan error on column index 0: unsupported driver -> Scan pair: string -> *time.Time
[]string{"15min", "15"}
2015/08/19 10:19:38 Problem while scanning query result: sql: Scan error on column index 0: unsupported driver -> Scan pair: string -> *time.Time
[]string{"day", "<nil>"}
2015/08/19 10:19:38 Problem while scanning query result: sql: Scan error on column index 0: unsupported driver -> Scan pair: string -> *time.Time
[]string{"hour", "40"}
```

Can someone please tell me if I am doing something wrong, or if this is a bug in the library?

### PR DESCRIPTION
**Pull request by philchia**
do not reuse conn after timeout err occurred

fix #119 though its closed

### CODE REVIEW

**Comment by captncraig** [comment]
I've been having issues with connections being in a bad state after the commit part of a bulk copy times out. I worked around it by setting a max connection age on my connection pool, but hopefully this will address the underlying cause. I will try to run this patch and see if it occurs again, but it is fairly hard to reproduce. Thanks!

**Comment by philchia** [comment]
With some hack I can reproduce this issue every single time:
**net.go**
```go
type timeoutConn struct {
	c             net.Conn
	timeout       time.Duration
	buf           *tdsBuffer
	packetPending bool
	continueRead  bool

	testtimeout   bool
	timeoutReader io.Reader
}

func (c *timeoutConn) Read(b []byte) (n int, err error) {
	if c.buf != nil {
		if c.packetPending {
			c.packetPending = false
			err = c.buf.FinishPacket()
			if err != nil {
				err = fmt.Errorf("Cannot send handshake packet: %s", err.Error())
				return
			}
			c.continueRead = false
		}
		if !c.continueRead {
			var packet uint8
			packet, err = c.buf.BeginRead()
			if err != nil {
				err = fmt.Errorf("Cannot read handshake packet: %s", err.Error())
				return
			}
			if packet != packPrelogin {
				err = fmt.Errorf("unexpected packet %d, expecting prelogin", packet)
				return
			}
			c.continueRead = true
		}
		n, err = c.buf.Read(b)
		return
	}
	err = c.c.SetDeadline(time.Now().Add(c.timeout))
	if err != nil {
		return
	}
	if c.testtimeout {
		if c.timeoutReader == nil {
			c.timeoutReader = iotest.TimeoutReader(c.c)
		}
		return c.timeoutReader.Read(b)
	}
	return c.c.Read(b)
}
```
**tds.go**
```go
func connect(params map[string]string) (res *tdsSession, err error) {
...
	if !success {
		return nil, fmt.Errorf("Login failed")
	}
	if sess.routedServer != "" {
		toconn.Close()
		p.host = sess.routedServer
		p.port = uint64(sess.routedPort)
		goto initiate_connection
	}
	toconn.testtimeout = true
	return &sess, nil
}
```

**Comment by kardianos** [comment]
These changes look sane. I'll test them and let likely merge them after.

**Comment by captncraig** [comment]
It looks like this probably works as intended, but it is a bit unfortunate that now I see `driver: bad connection` in my logs where I used to see things like `io timeout`. Is there any way to return the underlying error to the immediate caller, but still removing the connection from the pool?

**Comment by philchia** [comment]
The connection pool is managed by the database/sql package, it will removing the connection from the pool only if you return driver.ErrBadConn

**Comment by kardianos** [comment]
@captncraig That actually might be a good change for go1.10, allow wrapping an error in a known error type.

**Comment by denisenkom** [comment]
Same issue: #275

**Pull request merged**
