### PR TITLE
WIP table valued parameters (TVP)

### PR DESCRIPTION
**Pull request by elliots**
See: https://github.com/denisenkom/go-mssqldb/issues/263

Heyo. This is *very* work in progress. doesn't work. isn't close to working. 
but, its a start. putting here in case anyone has any hints or tips(@denisenkom @kardianos @judwhite)

I am muddling my way through, looking closely at the python driver and comparing output.

If anyone wants to put me out of my misery and finish it, please do. 
I'm even happy to pay you to do it :) (please email elliot - at - identitii.com)

It's failing with "panic: mssql: The incoming tabular data stream (TDS) protocol stream is incorrect. The stream ended unexpectedly." which is better than nothing. sort of.

### CODE REVIEW

**Comment by elliots** [comment]
This is my test code. The table and procedure code are generated from tsql (i'll open source it once we can actually use it :)

```golang
package main

import (
	"context"
	"database/sql"
	"fmt"
	"log"

	"github.com/davecgh/go-spew/spew"
	mssql "github.com/denisenkom/go-mssqldb"
	"github.com/jmoiron/sqlx"
)

/*
CREATE TABLE Person
(
    FullName                VARCHAR(500),
    City                    VARCHAR(500),
    AddressLine1            VARCHAR(500)
);

CREATE TYPE PersonAddressTable AS TABLE
(
    full_name           VARCHAR(500),
    city                VARCHAR(500),
    address_line_1      VARCHAR(500)
);
GO

CREATE PROCEDURE SavePeople
    @people PersonAddressTable READONLY
AS
BEGIN
    SET NOCOUNT ON;

    INSERT INTO Person(FullName, City, AddressLine1)
    SELECT  full_name, city, address_line_1
    FROM    @people;

    SELECT  AddressLine1, City, FullName
    FROM    Person;
END;
GO

*/

// Tables

type PersonAddressTable []PersonAddressTableRow

func (t *PersonAddressTable) TVP() *mssql.TableValuedParam {
	p := &mssql.TableValuedParam{
		TypeName: "dbo.PersonAddressTable",
	}
	for _, r := range *t {
		p.Rows = append(p.Rows, []interface{}{
			r.FullName,
			r.City,
			r.AddressLine1,
		})
	}
	return p
}

type PersonAddressTableRow struct {
	FullName     string `sql:"full_name"`
	City         string `sql:"city"`
	AddressLine1 string `sql:"address_line_1"`
}

// Procedures

// SavePeople calls the stored procedure SavePeople
func SavePeople(ctx context.Context, db *sqlx.DB, people *PersonAddressTable) (*sqlx.Rows, error) {
	// TODO: Add tracing/timing here.
	return db.Queryx("exec [dbo].[SavePeople] @People",
		sql.Named("People", people))
}

func main() {

	db, err := sqlx.Open("sqlserver", "server=localhost;user id=sa;password=mypassword123;port=1433")
	if err != nil {
		log.Fatal("Error connecting: " + err.Error())
	}
	log.Printf("Connected!\n")
	defer db.Close()

	ctx := context.Background()

	rows, err := SavePeople(ctx, db, &PersonAddressTable{
		/*PersonAddressTableRow{
			FullName:     "Chris",
			City:         "Sydney",
			AddressLine1: "Bondi",
		},*/
		PersonAddressTableRow{
			FullName:     "Ben",
			City:         "Sydney",
			AddressLine1: "Paddington",
		},
	})
	if err != nil {
		panic(err)
	}

	fmt.Println("result set")

	for rows.Next() {
		val := map[string]interface{}{}
		if err := rows.MapScan(val); err != nil {
			panic(err)
		}
		spew.Dump(val)
	}

}

```

**Comment by elliots** [comment]
For anyone attempting anything like this in the future... wireshark is super useful.

image

For some reason, the python driver output isn't parsed in as much detail, but still useful.

**Comment by denisenkom** [comment]
Can you add tests into test suite?

**Comment by elliots** [comment]
I'll tidy up and get a few tests in over the week based on my test code, but if anyone else has a chance to try it out on their own code I'd appreciate it.

**Comment by pokutnik** [comment]
Hi @elliots . Thanks for starting working on support for Table-Valued Parameters.
I've tried this brach and encountered a couple issues.
1. interface of `tvpWrapper` differs from the test code above, but that's minor.
2. panic around TODO note https://github.com/denisenkom/go-mssqldb/pull/413/files#diff-4ae3a9aff2782b92b61a1182be9b7d5fR38 :
```
panic(0x142d720, 0x182ae40)
        GOROOT/src/runtime/panic.go:513 +0x1b9
x/vendor/github.com/denisenkom/go-mssqldb.(*TableValuedParam).encode(0xc00034e0f0, 0x0, 0x0, 0x0, 0xf3, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        vendor/github.com/denisenkom/go-mssqldb/tvp.go:39 +0x12cd
x/vendor/github.com/denisenkom/go-mssqldb.(*Stmt).makeParamExtra(0xc00034e060, 0x1426f00, 0xc00034e0f0, 0x0, 0x0, 0x0, 0xf3, 0x0, 0x0, 0x0, ...)
        vendor/github.com/denisenkom/go-mssqldb/mssql_go19.go:186 +0xbe8
x/vendor/github.com/denisenkom/go-mssqldb.(*Stmt).makeParam(0xc00034e060, 0x1426f00, 0xc00034e0f0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        vendor/github.com/denisenkom/go-mssqldb/mssql.go:847 +0x2e6
x/vendor/github.com/denisenkom/go-mssqldb.(*Stmt).makeRPCParams(0xc00034e060, 0xc0003560f0, 0x6, 0x6, 0x2, 0x0, 0x0, 0x0, 0x0, 0x0, ...)
        vendor/github.com/denisenkom/go-mssqldb/mssql.go:531 +0x280
x/vendor/github.com/denisenkom/go-mssqldb.(*Stmt).sendQuery(0xc00034e060, 0xc0003560f0, 0x6, 0x6, 0x0, 0x0)
        vendor/github.com/denisenkom/go-mssqldb/mssql.go:454 +0x1146
x/vendor/github.com/denisenkom/go-mssqldb.(*Stmt).queryContext(0xc00034e060, 0x1516ba0, 0xc00001e0c0, 0xc0003560f0, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
        vendor/github.com/denisenkom/go-mssqldb/mssql.go:572 +0x9a
x/vendor/github.com/denisenkom/go-mssqldb.(*Stmt).QueryContext(0xc00034e060, 0x1516ba0, 0xc00001e0c0, 0xc000356000, 0x6, 0x6, 0x0, 0x0, 0x0, 0x0)
        vendor/github.com/denisenkom/go-mssqldb/mssql.go:950 +0x271
```
3. encoding `int, float` types in `func (s *Stmt) makeParam ...` function, but that's outside of current pull request.
4. I've got error `mssql: The incoming tabular data stream (TDS) remote procedure call (RPC) protocol stream is incorrect. Table-valued parameter 0 (""), row 0, column 0: Data type 0x26 has an invalid data length or metadata length.`

I can't share code to reproduce it or troubleshoot it with Wireshark, but i'll suggest test stored procedure with multiple tables parameters, and calling it with an empty table.

**Comment by elliots** [comment]
Thanks for testing pokutnik! I've expanded my test case slightly, and cleaned up a few things. Empty tables, and more param types are supported. (The code to check if a column size should be provided is dumb.)

The tvp interface now requires an "example" row in order to work out column types if there are no data rows provided (or nil PersonAddressTable). Its a bit ugly, but im generating anyway so not much work for me. Not sure how to do that better. Certainly for a start by supporting default values, which it currently does not.

```
// SavePeople calls the stored procedure SavePeople
func SavePeople(ctx context.Context, db Queryer, people *PersonAddressTable) (*sqlx.Rows, error) {
	// TODO: Add tracing/timing here.
	return db.QueryxContext(ctx,
		"exec SavePeople @people",
		sql.Named("people", people))
}

type PersonAddressTable []PersonAddressTableRow

func (t *PersonAddressTable) TVP() (typeName string, exampleRow []interface{}, rows [][]interface{}) {
	typeName = "PersonAddressTable"
	var v []PersonAddressTableRow
	if t != nil {
		v = *t
	}
	for _, r := range append(v, PersonAddressTableRow{}) {
		rows = append(rows, []interface{}{
			r.FullName,
			r.City,
			r.AddressLine1,
			r.DocumentID,
			r.DocumentType,
			r.DocumentHash,
			r.DocumentData,
			r.DocumentVersion,
			r.ShardID,
		})
	}
	exampleRow = rows[len(rows)-1]
	rows = rows[:len(rows)-1]

	return
}

type PersonAddressTableRow struct {
	FullName        string                 `db:"full_name"`
	City            string                 `db:"city"`
	AddressLine1    string                 `db:"address_line_1"`
	DocumentID      mssql.UniqueIdentifier `db:"document_id"`
	DocumentType    string                 `db:"document_type"`
	DocumentHash    []byte                 `db:"document_hash"`
	DocumentData    []byte                 `db:"document_data"`
	DocumentVersion string                 `db:"document_version"`
	ShardID         int16                  `db:"shard_id"`
}```

```

CREATE TABLE Person
(
    FullName                VARCHAR(500),
    City                    VARCHAR(500),
    AddressLine1            VARCHAR(500)
);

CREATE TYPE PersonAddressTable AS TABLE   
( 
    full_name           VARCHAR(500), 
    city                VARCHAR(500),
    address_line_1      VARCHAR(500),
    document_id         UNIQUEIDENTIFIER, 
    document_type       NVARCHAR(130),
    document_hash       BINARY(256),
    document_data       VARBINARY(MAX),
    document_version    VARCHAR(500),
    shard_id            SMALLINT
);  
GO 

CREATE PROCEDURE SavePeople
    @people PersonAddressTable READONLY
AS   
BEGIN
    SET NOCOUNT ON; 

    INSERT INTO Person(FullName, City, AddressLine1)
    SELECT  full_name, city, address_line_1
    FROM    @people;

    SELECT  AddressLine1, City, FullName
    FROM    Person;
END;
GO 
```

**Comment by ilusharulkov** [comment]
Hi guys!
Are there any predictions about merge in the master branch?

**Comment by elliots** [comment]
My branch is currently working enough for my use... and I'll open source the code generator that creates binding from sprocs->go. 

What it needs before we can merge:
  - People to use and find the problems (@ilusharulkov @pokutnik)
  - More tests, the current one is mostly based around my use case. More people using will find more things to test.
  - Some cleanup

**Comment by LogikBlitz** [comment]
>     * People to use and find the problems

@elliots i would like to test this functionality. Can you provide access to the branch/package ?Also did you opensource your sprocs -> go

**Comment by LogikBlitz** [comment]
Hi @elliots @denisenkom 
Are there still anything holding the merge back?
I am working with the tvp branch fork by @elliots but it is already behind.

**Comment by elliots** [comment]
I started releasing the generator the other day when you posted, but got distracted. I'll try and finish it today, and rebase the branch.

I think it needs at least another test or two, and one more person to say it's working :)

**Comment by elliots** [comment]
Ok, the tool is online... https://github.com/identitii/sprocbind
And I've squashed and rebased

With the tests, at least checking a lot more data types would make sense. There is one part where I have a list of types that I need to hide the length value of, and I have no idea how accurate or complete it is. It works, but I don't understand it... also the life of anyone in IT :)

**Comment by kardianos** [comment]
I'm happy to see this worked on!

The code needs to be cleaned up a bit, and in this case, I'd like a bit more docs, or at least references to documentation.  Start with removing old comments, and add a user facing example how to use TVP if you wouldn't mind.

**Comment by infomediadev** [comment]
I have been really busy and will be for the the rest of the year. Ill see how much i can do on this to get it merged.

**Comment by LogikBlitz** [comment]
I am really busy for at least the remainder of the year. Ill see how much i can get done on this issue in order to merge.

**Comment by majidbigdeli** [comment]
when PR is accepted ?

**Comment by kardianos** [comment]
I'm not seeing any of my previous comments addressed. @majidbigdeli @shaileshpandey I appreciate your enthusiasm, but nothing has changed from my previous review.

@elliots Do you want someone else to pick up the PR where you've left it?

**Comment by elliots** [comment]
That's right, it's not ready to merge yet. I'm back after the break now so I'll try and get to this in the next 3-4 days.

**Comment by denisenkom** [comment]
I believe this PR is no longer needed, since https://github.com/denisenkom/go-mssqldb/pull/447 was merged.

**Comment by elliots** [comment]
Awesome 👍

**Pull request closed without merging**
